version: "3.9"

services:
  hawkeyedb:
    container_name: hawkeyedb
    image: postgres:14
    volumes:
      - hawkeyedb:/var/lib/postgresql/data
    ports:
      - 5433:5432
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  hawkeyedb-migration:
    container_name: hawkeyedb-migration
    build: ./migration
    depends_on:
      hawkeyedb:
        condition: service_healthy
    env_file:
      - .env

  hawkeye:
    container_name: hawkeye
    build:
      context: .
    depends_on:
      hawkeyedb:
        condition: service_healthy
    env_file:
      - .env

volumes:
  hawkeyedb:
