apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.hawkeyedb.name }}-migration
  labels:
    app: {{ .Values.hawkeyedb.name }}-migration 
spec:
  backoffLimit: 5
  template:
    metadata:
      labels:
        app: {{ .Values.hawkeyedb.name }}-migration
    spec:
      restartPolicy: OnFailure
      containers:
        - name: {{ .Values.hawkeyedb.name }}-migration
          image: {{ .Values.hawkeye.migration.image }}:{{ default .Chart.AppVersion .Values.version }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command:
            - migration
          args:
            - up
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.hawkeye.name }}-secrets
                  key: DATABASE_URL
