apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.hawkeye.name }}-secrets
type: Opaque
data:
  POSTGRES_DB: {{ .Values.secrets.POSTGRES_DB | b64enc | quote }}
  POSTGRES_USER: {{ .Values.secrets.POSTGRES_USER | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.POSTGRES_PASSWORD | b64enc | quote }}    
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | b64enc | quote }}
  NATALIE_WEBHOOK_URL: {{ .Values.secrets.NATALIE_WEBHOOK_URL | b64enc | quote }}
  BROWSER_DRIVER_URL: {{ .Values.secrets.BROWSER_DRIVER_URL | b64enc | quote }}
