name: Deploy
on:
  push:
    tags:
      - 'v*.*.*'

  workflow_dispatch:

jobs:
  migration:
    name: Build & Push Migration
    runs-on: ubuntu-latest
    if: {{ github.ref == 'ref/head/main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Image Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ secrets.MIGRATION_DOCKER_IMAGE }}
          tags: |
            type=semver,pattern={{version}}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: migration 
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  hawkeye:
    name: Build & Push
    runs-on: ubuntu-latest
    if: {{ github.ref == 'ref/head/main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Image Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ secrets.DOCKER_IMAGE }}
          tags: |
            type=semver,pattern={{version}}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
