name: Deploy
on:
  push:
    tags:
      - 'v*.*.*'

  workflow_dispatch:

jobs:
  # Why must I go to such lengths just to run a workflow
  # when I push a tag only for the main branch!?
  check:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.check_step.outputs.branch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get current branch
        id: check_step
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw##*/}
          echo "::set-output name=branch::$branch"
          echo "Branch is $branch."
  
  # Workaround since ArgoCD doesn't support tag pattern matching
  tag:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.branch == 'main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update production tag
        run: git tag production --force && git push origin production --force

  migration:
    name: Build & Push Migration
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.branch == 'main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Image Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ secrets.MIGRATION_DOCKER_IMAGE }}
          tags: |
            type=semver,pattern={{version}}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: migration 
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  hawkeye:
    name: Build & Push
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.branch == 'main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Image Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ secrets.DOCKER_IMAGE }}
          tags: |
            type=semver,pattern={{version}}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
